FROM python:alpine3.15

COPY generate-random-data/. ./

RUN apk update
RUN apk add --no-cache gcc musl-dev libc-dev linux-headers librdkafka librdkafka-dev
RUN pip3 install --upgrade pip

RUN pip install -r requirements.txt


CMD ["python3", "generate_user_data.py"]