FROM python:alpine3.15
WORKDIR /code
COPY generate-random-data/. ./

RUN apk update
RUN apk add --no-cache gcc musl-dev libc-dev linux-headers librdkafka librdkafka-dev
RUN pip3 install --upgrade pip

RUN pip install -r requirements.txt


ENTRYPOINT ["python3", "producer.py", "-c", "10"]